# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete --exclude=".git" --exclude=".github"
        path: ./build/
    remote_path: /var/www/html/emd_frontend_gitAction
    remote_host: ${{ secrets.SSH_HOST }}
    remote_user: ${{ secrets.SSH_USERNAME }}
    remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
